"""initial schema

Revision ID: 61eb69034254
Revises: 
Create Date: 2026-07-06 15:44:21.721010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '61eb69034254'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('broker', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lane_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('lane', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('artifact', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lane_runs_account_id'), 'lane_runs', ['account_id'], unique=False)
    op.create_index(op.f('ix_lane_runs_lane'), 'lane_runs', ['lane'], unique=False)
    op.create_index(op.f('ix_lane_runs_status'), 'lane_runs', ['status'], unique=False)
    op.create_table('param_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('param_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.String(length=100), nullable=True),
    sa.Column('new_value', sa.String(length=100), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_param_history_account_id'), 'param_history', ['account_id'], unique=False)
    op.create_index(op.f('ix_param_history_param_name'), 'param_history', ['param_name'], unique=False)
    op.create_table('sleeves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('budget_fraction', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('drawdown_halt_fraction', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('halted', sa.Boolean(), nullable=False),
    sa.Column('hwm', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'type', name='uq_sleeves_account_type')
    )
    op.create_index(op.f('ix_sleeves_account_id'), 'sleeves', ['account_id'], unique=False)
    op.create_table('theses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('sleeve_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('instrument', sa.String(length=20), nullable=False),
    sa.Column('entry', sa.Text(), nullable=False),
    sa.Column('exit', sa.Text(), nullable=False),
    sa.Column('invalidation', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['sleeve_id'], ['sleeves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theses_account_id'), 'theses', ['account_id'], unique=False)
    op.create_index(op.f('ix_theses_sleeve_id'), 'theses', ['sleeve_id'], unique=False)
    op.create_index(op.f('ix_theses_status'), 'theses', ['status'], unique=False)
    op.create_index(op.f('ix_theses_symbol'), 'theses', ['symbol'], unique=False)
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rubric', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grades_account_id'), 'grades', ['account_id'], unique=False)
    op.create_index(op.f('ix_grades_thesis_id'), 'grades', ['thesis_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=True),
    sa.Column('ref_id', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('notional', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gate_verdict', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_id')
    )
    op.create_index(op.f('ix_orders_account_id'), 'orders', ['account_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_thesis_id'), 'orders', ['thesis_id'], unique=False)
    op.create_table('fills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fills_account_id'), 'fills', ['account_id'], unique=False)
    op.create_index(op.f('ix_fills_order_id'), 'fills', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fills_order_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_account_id'), table_name='fills')
    op.drop_table('fills')
    op.drop_index(op.f('ix_orders_thesis_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_account_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_grades_thesis_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_account_id'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_theses_symbol'), table_name='theses')
    op.drop_index(op.f('ix_theses_status'), table_name='theses')
    op.drop_index(op.f('ix_theses_sleeve_id'), table_name='theses')
    op.drop_index(op.f('ix_theses_account_id'), table_name='theses')
    op.drop_table('theses')
    op.drop_index(op.f('ix_sleeves_account_id'), table_name='sleeves')
    op.drop_table('sleeves')
    op.drop_index(op.f('ix_param_history_param_name'), table_name='param_history')
    op.drop_index(op.f('ix_param_history_account_id'), table_name='param_history')
    op.drop_table('param_history')
    op.drop_index(op.f('ix_lane_runs_status'), table_name='lane_runs')
    op.drop_index(op.f('ix_lane_runs_lane'), table_name='lane_runs')
    op.drop_index(op.f('ix_lane_runs_account_id'), table_name='lane_runs')
    op.drop_table('lane_runs')
    op.drop_table('accounts')
    # ### end Alembic commands ###
